env.workspace = 'example'
pipeline{
	agent {docker {image 'mrchecker/mrchecker:v1.1.3'}}
	stages{
		stage('Build'){
			steps{
				configFileProvider([configFile(fileId: 'deploy-maven-settings', targetLocation: 'settings.xml', variable: 'SETTINGS_PATH')]) {
					echo "Building project"
					sh \"\"\"
					cd ${env.workspace}
					mvn -q -s ${SETTINGS_PATH} clean compile test-compile package install -DskipTests=true
					\"\"\"
				}
				//bulid this module and its dependencies deploy them to local repo
			}
		}
		stage('Test1'){
			steps{
				configFileProvider([configFile(fileId: 'deploy-maven-settings', targetLocation: 'settings.xml', variable: 'SETTINGS_PATH')]) {
					echo "Testing"
					sh \"\"\"
					cd ${env.workspace}
					mvn -q -s ${SETTINGS_PATH} clean test -Dbrowser=firefox -DseleniumGrid=http://10.40.234.103:4444/wd/hub -Ddebug -Dgroups=MTS_GUI,MTS_API allure:report
					\"\"\"
					allure includeProperties: false, jdk: '', report: "allure-report-run1", results: [[path: "${env.workspace}/target/allure-results"]]
				}
			}
		}
		stage('Test2'){
			steps{
				configFileProvider([configFile(fileId: 'deploy-maven-settings', targetLocation: 'settings.xml', variable: 'SETTINGS_PATH')]) {
					echo "Testing"
					sh \"\"\"
					cd ${env.workspace}
					mvn -q -s ${SETTINGS_PATH} -Pcucumber clean verify -Dbrowser=firefox -DseleniumGrid=http://10.40.234.103:4444/wd/hub -Denv=QA -Dcucumber.class=RunMts* allure:report 
					\"\"\"
					allure includeProperties: false, jdk: '', report: "allure-report-run2", results: [[path: "${env.workspace}/target/allure-results"]]
				}
			}
		}
	}
}
